var g;g||=typeof Module != 'undefined' ? Module : {};var aa=!!globalThis.window,ba=!!globalThis.WorkerGlobalScope,ca=globalThis.process?.versions?.node&&globalThis.process?.type!="renderer",da=[],ea="./this.program",fa=(a,b)=>{throw b;},ha=globalThis.document?.currentScript?.src;typeof __filename!="undefined"?ha=__filename:ba&&(ha=self.location.href);var ia="",ja,ka;
if(ca){var fs=require("node:fs");ia=__dirname+"/";ka=a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a)};ja=async a=>{a=la(a)?new URL(a):a;return fs.readFileSync(a,void 0)};process.argv.length>1&&(ea=process.argv[1].replace(/\\/g,"/"));da=process.argv.slice(2);typeof module!="undefined"&&(module.exports=g);fa=(a,b)=>{process.exitCode=a;throw b;}}else if(aa||ba){try{ia=(new URL(".",ha)).href}catch{}ba&&(ka=a=>{var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";b.send(null);return new Uint8Array(b.response)});
ja=async a=>{if(la(a))return new Promise((c,d)=>{var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=()=>{e.status==200||e.status==0&&e.response?c(e.response):d(e.status)};e.onerror=d;e.send(null)});var b=await fetch(a,{credentials:"same-origin"});if(b.ok)return b.arrayBuffer();throw Error(b.status+" : "+b.url);}}console.log.bind(console);var k=console.error.bind(console),m,q=!1,ma,la=a=>a.startsWith("file://");
function na(){var a=oa.buffer;t=new Int8Array(a);pa=new Int16Array(a);g.HEAPU8=u=new Uint8Array(a);qa=new Uint16Array(a);v=new Int32Array(a);w=new Uint32Array(a);x=new Float32Array(a);y=new Float64Array(a);new BigInt64Array(a);new BigUint64Array(a)}function ra(a){g.onAbort?.(a);a=`Aborted(${a})`;k(a);q=!0;throw new WebAssembly.RuntimeError(a+". Build with -sASSERTIONS for more info.");}var sa;
async function ta(a){if(!m)try{var b=await ja(a);return new Uint8Array(b)}catch{}if(a==sa&&m)a=new Uint8Array(m);else if(ka)a=ka(a);else throw"both async and sync fetching of the wasm failed";return a}async function ua(a,b){try{var c=await ta(a);return await WebAssembly.instantiate(c,b)}catch(d){k(`failed to asynchronously prepare wasm: ${d}`),ra(d)}}
async function va(a){var b=sa;if(!m&&!la(b)&&!ca)try{var c=fetch(b,{credentials:"same-origin"});return await WebAssembly.instantiateStreaming(c,a)}catch(d){k(`wasm streaming compile failed: ${d}`),k("falling back to ArrayBuffer instantiation")}return ua(b,a)}class wa{name="ExitStatus";constructor(a){this.message=`Program terminated with exit(${a})`;this.status=a}}
var pa,v,t,x,y,qa,w,u,xa=a=>{for(;a.length>0;)a.shift()(g)},ya=[],za=[],Aa=()=>{var a=g.preRun.shift();za.push(a)},z=0,A=null,Ba=!0,Ca=0,B={},Da=a=>{a instanceof wa||a=="unwind"||fa(1,a)},Ea=a=>{ma=a;Ba||Ca>0||(g.onExit?.(a),q=!0);fa(a,new wa(a))},Fa=()=>{if(!(Ba||Ca>0))try{var a=ma;ma=a;Ea(a)}catch(b){Da(b)}},Ga=a=>{if(!q)try{a()}catch(b){Da(b)}finally{Fa()}},Oa=(a,b)=>{Ha=a;Ia=b;if(D)if(Ja||=!0,a==0)E=function(){setTimeout(Ka,Math.max(0,La+b-performance.now())|0)};else if(a==1)E=function(){Ma(Ka)};
else{if(!Na)if(globalThis.scheduler)Na=scheduler.postTask.bind(scheduler);else if(globalThis.setImmediate)Na=setImmediate;else{var c=[];addEventListener("message",d=>{d.data==="setimmediate"&&(d.stopPropagation(),c.shift()())},!0);Na=d=>{c.push(d);ba?postMessage("setimmediate"):postMessage("setimmediate","*")}}E=function(){Na(Ka)}}},Xa=(a,b,c,d,e)=>{function h(){return f<Pa?(Fa(),!1):!0}D=a;Qa=d;var f=Pa;Ja=!1;Ka=function(){if(!q)if(Ra.length>0){var l=Ra.shift();l.Od(l.Cd);if(Sa){var n=Sa,p=n%1==
0?n-1:Math.floor(n);Sa=l.Fd?p:(8*n+(p+.5))/9}g.setStatus&&(l=g.statusMessage||"Please wait...",n=Sa??0,p=Ta.Ld??0,n?n<p?g.setStatus("{message} ({expected - remaining}/{expected})"):g.setStatus(l):g.setStatus(""));h()&&setTimeout(Ka,0)}else if(h())if(Ua=Ua+1|0,Ha==1&&Ia>1&&Ua%Ia!=0)E();else{Ha==0&&(La=performance.now());a:if(!q){for(l of Va)if(l()===!1)break a;Ga(a);for(n of Wa)n()}h()&&E()}};e||(b>0?Oa(0,1E3/b):Oa(1,1),E());if(c)throw"unwind";},Ja=!1,E=null,Pa=0,D=null,Qa=0,Ha=0,Ia=0,Ua=0,Ra=[],Va=
[],Wa=[];function Ya(){E=null;Pa++}var Za=0;function Ma(a){if(globalThis.requestAnimationFrame)requestAnimationFrame(a);else{var b=Date.now();if(Za===0)Za=b+1E3/60;else for(;b+2>=Za;)Za+=1E3/60;setTimeout(a,Math.max(Za-b,0))}}
var Ta={},La,Ka,Na,Sa,$a=globalThis.TextDecoder&&new TextDecoder,F=(a=0,b)=>{var c=u;var d=a;for(b=d+b;c[d]&&!(d>=b);)++d;if(d-a>16&&c.buffer&&$a)return $a.decode(c.subarray(a,d));for(b="";a<d;){var e=c[a++];if(e&128){var h=c[a++]&63;if((e&224)==192)b+=String.fromCharCode((e&31)<<6|h);else{var f=c[a++]&63;e=(e&240)==224?(e&15)<<12|h<<6|f:(e&7)<<18|h<<12|f<<6|c[a++]&63;e<65536?b+=String.fromCharCode(e):(e-=65536,b+=String.fromCharCode(55296|e>>10,56320|e&1023))}}else b+=String.fromCharCode(e)}return b},
ab=[0,globalThis.document??0,globalThis.window??0],G=a=>{a=a>2?a?F(a):"":a;return ab[a]||globalThis.document?.querySelector(a)},bb=a=>ab.indexOf(a)<0?a.getBoundingClientRect():{left:0,top:0},cb=[],H=a=>{var b=cb[a];b||(cb[a]=b=db.get(a));return b};function eb(a){var b=I.Ac[a];b.target.removeEventListener(b.zc,b.gd,b.Dc);I.Ac.splice(a,1)}function fb(){if(navigator.userActivation?navigator.userActivation.isActive:I.Tc&&I.wd.Qc){var a=I.Ic;I.Ic=[];for(var b of a)b.Wc(...b.bd)}}
function J(a){if(!a.target)return-4;if(a.Bc)a.gd=function(c){++I.Tc;I.wd=a;fb();a.Fc(c);fb();--I.Tc},a.target.addEventListener(a.zc,a.gd,a.Dc),I.Ac.push(a);else for(var b=0;b<I.Ac.length;++b)I.Ac[b].target==a.target&&I.Ac[b].zc==a.zc&&eb(b--);return 0}function gb(a){return a==window?"#window":a==screen?"#screen":a?.nodeName??""}
var I={Dd:0,Pd:0,Uc:0,Oc:0,$c:0,Yc:0,Rc:0,Jd:0,Td:0,Id:0,Sc:0,Vc:0,be:0,Xc:0,Vd(){for(;I.Ac.length;)eb(I.Ac.length-1);I.Ic=[]},Tc:0,Ic:[],Hd(a,b,c){function d(h,f){if(h.length!=f.length)return!1;for(var l in h)if(h[l]!=f[l])return!1;return!0}for(var e of I.Ic)if(e.Wc==a&&d(e.bd,c))return;I.Ic.push({Wc:a,ld:b,bd:c});I.Ic.sort((h,f)=>h.ld-f.ld)},Xd(a){I.Ic=I.Ic.filter(b=>b.Wc!=a)},Ac:[],Wd:(a,b)=>{for(var c=0;c<I.Ac.length;++c)I.Ac[c].target!=a||b&&b!=I.Ac[c].zc||eb(c--)},Yd(a){var b=!1;for(let c=0;c<
I.Ac.length;++c){let d=I.Ac[c];d.target===a.target&&d.Cc===a.Cc&&d.Bc===a.Bc&&d.Ec===a.Ec&&(eb(c--),b=!0)}return b?0:-5},fullscreenEnabled(){return document.fullscreenEnabled||document.webkitFullscreenEnabled}},K=(a,b,c)=>{var d=u;if(!(c>0))return 0;var e=b;c=b+c-1;for(var h=0;h<a.length;++h){var f=a.codePointAt(h);if(f<=127){if(b>=c)break;d[b++]=f}else if(f<=2047){if(b+1>=c)break;d[b++]=192|f>>6;d[b++]=128|f&63}else if(f<=65535){if(b+2>=c)break;d[b++]=224|f>>12;d[b++]=128|f>>6&63;d[b++]=128|f&63}else{if(b+
3>=c)break;d[b++]=240|f>>18;d[b++]=128|f>>12&63;d[b++]=128|f>>6&63;d[b++]=128|f&63;h++}}d[b]=0;return b-e},hb=(a,b,c,d,e,h)=>{I.Rc||(I.Rc=L(256));a={target:G(a),zc:h,Cc:e,Ec:b,Bc:d,Fc:f=>{var l=f.target.id??"",n=I.Rc;K(gb(f.target),n+0,128);K(l,n+128,128);H(d)(e,n,b)&&f.preventDefault()},Dc:c};return J(a)},ib=(a,b,c,d,e)=>{I.Sc||(I.Sc=L(276));return J({target:a,zc:e,Cc:19,Ec:b,Bc:d,Fc:h=>{var f=I.Sc,l=document.fullscreenElement||document.mozFullScreenElement||document.webkitFullscreenElement||document.webkitCurrentFullScreenElement||
document.msFullscreenElement,n=!!l;t[f]=n;t[f+1]=I.fullscreenEnabled();var p=n?l:I.Ad,r=p?.id??"";K(gb(p),f+2,128);K(r,f+130,128);v[f+260>>2]=p?.clientWidth??0;v[f+264>>2]=p?.clientHeight??0;v[f+268>>2]=screen.width;v[f+272>>2]=screen.height;n&&(I.Ad=l);H(d)(19,f,b)&&h.preventDefault()},Dc:c})},jb=(a,b,c,d,e,h)=>{I.Uc||(I.Uc=L(160));a={target:G(a),zc:h,Cc:e,Ec:b,Bc:d,Fc:f=>{var l=I.Uc;y[l>>3]=f.timeStamp;var n=l>>2;v[n+2]=f.location;t[l+12]=f.ctrlKey;t[l+13]=f.shiftKey;t[l+14]=f.altKey;t[l+15]=f.metaKey;
t[l+16]=f.repeat;v[n+5]=f.charCode;v[n+6]=f.keyCode;v[n+7]=f.which;K(f.key??"",l+32,32);K(f.code??"",l+64,32);K(f.char??"",l+96,32);K(f.locale??"",l+128,32);H(d)(e,l,b)&&f.preventDefault()},Dc:c};return J(a)},kb=(a,b,c)=>{y[a>>3]=b.timeStamp;var d=a>>2;v[d+2]=b.screenX;v[d+3]=b.screenY;v[d+4]=b.clientX;v[d+5]=b.clientY;t[a+24]=b.ctrlKey;t[a+25]=b.shiftKey;t[a+26]=b.altKey;t[a+27]=b.metaKey;pa[d*2+14]=b.button;pa[d*2+15]=b.buttons;v[d+8]=b.movementX;v[d+9]=b.movementY;a=bb(c);v[d+10]=b.clientX-(a.left|
0);v[d+11]=b.clientY-(a.top|0)},lb=(a,b,c,d,e,h)=>{I.Oc||(I.Oc=L(64));a=G(a);return J({target:a,Qc:h!="mousemove"&&h!="mouseenter"&&h!="mouseleave",zc:h,Cc:e,Ec:b,Bc:d,Fc:f=>{kb(I.Oc,f,a);H(d)(e,I.Oc,b)&&f.preventDefault()},Dc:c})},mb=(a,b,c,d)=>{I.Vc||(I.Vc=L(257));return J({target:a,zc:"pointerlockchange",Cc:20,Ec:b,Bc:d,Fc:e=>{var h=I.Vc,f=document.pointerLockElement;t[h]=!!f;var l=f?.id??"";K(gb(f),h+1,128);K(l,h+129,128);H(d)(20,h,b)&&e.preventDefault()},Dc:c})},nb=(a,b,c,d)=>J({target:a,zc:"pointerlockerror",
Cc:38,Ec:b,Bc:d,Fc:e=>{H(d)(38,0,b)&&e.preventDefault()},Dc:c}),ob=(a,b,c,d)=>{I.Yc||(I.Yc=L(36));a=G(a);return J({target:a,zc:"resize",Cc:10,Ec:b,Bc:d,Fc:e=>{if(e.target==a){var h=document.body;if(h){var f=I.Yc;v[f>>2]=0;v[f+4>>2]=h.clientWidth;v[f+8>>2]=h.clientHeight;v[f+12>>2]=innerWidth;v[f+16>>2]=innerHeight;v[f+20>>2]=outerWidth;v[f+24>>2]=outerHeight;v[f+28>>2]=pageXOffset|0;v[f+32>>2]=pageYOffset|0;H(d)(10,f,b)&&e.preventDefault()}}},Dc:c})},pb=(a,b,c,d,e,h)=>{I.Xc||(I.Xc=L(1552));a=G(a);
return J({target:a,Qc:h=="touchstart"||h=="touchend",zc:h,Cc:e,Ec:b,Bc:d,Fc:f=>{var l={},n=f.touches;for(var p of n)p.hd=p.kd=0,l[p.identifier]=p;for(var r of f.changedTouches)r.hd=1,l[r.identifier]=r;for(var N of f.targetTouches)l[N.identifier].kd=1;n=I.Xc;y[n>>3]=f.timeStamp;t[n+12]=f.ctrlKey;t[n+13]=f.shiftKey;t[n+14]=f.altKey;t[n+15]=f.metaKey;p=n+16;r=bb(a);N=0;for(let C of Object.values(l))if(l=p>>2,v[l]=C.identifier,v[l+1]=C.screenX,v[l+2]=C.screenY,v[l+3]=C.clientX,v[l+4]=C.clientY,v[l+5]=
C.pageX,v[l+6]=C.pageY,t[p+28]=C.hd,t[p+29]=C.kd,v[l+8]=C.clientX-(r.left|0),v[l+9]=C.clientY-(r.top|0),p+=48,++N>31)break;v[n+8>>2]=N;H(d)(e,n,b)&&f.preventDefault()},Dc:c})},M,qb=a=>{var b=a.getExtension("ANGLE_instanced_arrays");b&&(a.vertexAttribDivisor=(c,d)=>b.vertexAttribDivisorANGLE(c,d),a.drawArraysInstanced=(c,d,e,h)=>b.drawArraysInstancedANGLE(c,d,e,h),a.drawElementsInstanced=(c,d,e,h,f)=>b.drawElementsInstancedANGLE(c,d,e,h,f))},rb=a=>{var b=a.getExtension("OES_vertex_array_object");b&&
(a.createVertexArray=()=>b.createVertexArrayOES(),a.deleteVertexArray=c=>b.deleteVertexArrayOES(c),a.bindVertexArray=c=>b.bindVertexArrayOES(c),a.isVertexArray=c=>b.isVertexArrayOES(c))},sb=a=>{var b=a.getExtension("WEBGL_draw_buffers");b&&(a.drawBuffers=(c,d)=>b.drawBuffersWEBGL(c,d))},tb=a=>{var b="ANGLE_instanced_arrays EXT_blend_minmax EXT_disjoint_timer_query EXT_frag_depth EXT_shader_texture_lod EXT_sRGB OES_element_index_uint OES_fbo_render_mipmap OES_standard_derivatives OES_texture_float OES_texture_half_float OES_texture_half_float_linear OES_vertex_array_object WEBGL_color_buffer_float WEBGL_depth_texture WEBGL_draw_buffers EXT_color_buffer_float EXT_conservative_depth EXT_disjoint_timer_query_webgl2 EXT_texture_norm16 NV_shader_noperspective_interpolation WEBGL_clip_cull_distance EXT_clip_control EXT_color_buffer_half_float EXT_depth_clamp EXT_float_blend EXT_polygon_offset_clamp EXT_texture_compression_bptc EXT_texture_compression_rgtc EXT_texture_filter_anisotropic KHR_parallel_shader_compile OES_texture_float_linear WEBGL_blend_func_extended WEBGL_compressed_texture_astc WEBGL_compressed_texture_etc WEBGL_compressed_texture_etc1 WEBGL_compressed_texture_s3tc WEBGL_compressed_texture_s3tc_srgb WEBGL_debug_renderer_info WEBGL_debug_shaders WEBGL_lose_context WEBGL_multi_draw WEBGL_polygon_mode".split(" ");
return a.getSupportedExtensions()?.filter(c=>b.includes(c))??[]},ub=1,O=[],P=[],vb=[],wb=[],Q=[],R=[],xb=[],yb=[],S=[],zb={},Ab=4,Bb=0,Cb=a=>{for(var b=ub++,c=a.length;c<b;c++)a[c]=null;return b},U=(a,b,c,d)=>{for(var e=0;e<a;e++){var h=M[c](),f=h&&Cb(d);h?(h.name=f,d[f]=h):T||=1282;v[b+e*4>>2]=f}},Eb=(a,b)=>{a.vd||(a.vd=a.getContext,a.getContext=function(d,e){e=a.vd(d,e);return d=="webgl"==e instanceof WebGLRenderingContext?e:null});var c=b.jd>1?a.getContext("webgl2",b):a.getContext("webgl",b);return c?
Db(c,b):0},Db=(a,b)=>{var c=Cb(yb),d={handle:c,attributes:b,version:b.jd,ad:a};a.canvas&&(a.canvas.Bd=d);yb[c]=d;if(typeof b.ed=="undefined"||b.ed)if((a=d)||(a=V),!a.zd){a.zd=!0;b=a.ad;b.Sd=b.getExtension("WEBGL_multi_draw");b.Nd=b.getExtension("EXT_polygon_offset_clamp");b.Md=b.getExtension("EXT_clip_control");b.ce=b.getExtension("WEBGL_polygon_mode");qb(b);rb(b);sb(b);b.Kd=b.getExtension("WEBGL_draw_instanced_base_vertex_base_instance");b.Qd=b.getExtension("WEBGL_multi_draw_instanced_base_vertex_base_instance");
a.version>=2&&(b.dd=b.getExtension("EXT_disjoint_timer_query_webgl2"));if(a.version<2||!b.dd)b.dd=b.getExtension("EXT_disjoint_timer_query");for(var e of tb(b))e.includes("lose_context")||e.includes("debug")||b.getExtension(e)}return c},T,V,Fb=(a,b,c,d,e,h)=>{a={target:G(a),zc:h,Cc:e,Ec:b,Bc:d,Fc:f=>{H(d)(e,0,b)&&f.preventDefault()},Dc:c};J(a)},Gb=(a,b,c,d)=>{I.$c||(I.$c=L(96));return J({target:a,Qc:!0,zc:"wheel",Cc:9,Ec:b,Bc:d,Fc:e=>{var h=I.$c;kb(h,e,a);y[h+64>>3]=e.deltaX;y[h+72>>3]=e.deltaY;y[h+
80>>3]=e.deltaZ;v[h+88>>2]=e.deltaMode;H(d)(9,h,b)&&e.preventDefault()},Dc:c})},Hb=["default","low-power","high-performance"],Ib=[],Jb=()=>{var a=tb(M);return a=a.concat(a.map(b=>"GL_"+b))},Kb=(a,b)=>{if(b){var c=void 0;switch(a){case 36346:c=1;break;case 36344:return;case 34814:case 36345:c=0;break;case 34466:var d=M.getParameter(34467);c=d?d.length:0;break;case 33309:if(V.version<2){T||=1282;return}c=Jb().length;break;case 33307:case 33308:if(V.version<2){T||=1280;return}c=a==33307?3:0}if(c===void 0)switch(d=
M.getParameter(a),typeof d){case "number":c=d;break;case "boolean":c=d?1:0;break;case "string":T||=1280;return;case "object":if(d===null)switch(a){case 34964:case 35725:case 34965:case 36006:case 36007:case 32873:case 34229:case 36662:case 36663:case 35053:case 35055:case 36010:case 35097:case 35869:case 32874:case 36389:case 35983:case 35368:case 34068:c=0;break;default:T||=1280;return}else{if(d instanceof Float32Array||d instanceof Uint32Array||d instanceof Int32Array||d instanceof Array){for(a=
0;a<d.length;++a)v[b+a*4>>2]=d[a];return}try{c=d.name|0}catch(e){T||=1280;k(`GL_INVALID_ENUM in glGet0v: Unknown object returned from WebGL getParameter(${a})! (error: ${e})`);return}}break;default:T||=1280;k(`GL_INVALID_ENUM in glGet0v: Native code calling glGet0v(${a}) and it returns ${d} of type ${typeof d}!`);return}v[b>>2]=c}else T||=1281},Lb=a=>{for(var b=0,c=0;c<a.length;++c){var d=a.charCodeAt(c);d<=127?b++:d<=2047?b+=2:d>=55296&&d<=57343?(b+=4,++c):b+=3}return b},Mb=a=>{var b=Lb(a)+1,c=L(b);
c&&K(a,c,b);return c},Nb=a=>a.slice(-1)=="]"&&a.lastIndexOf("["),Ob=a=>{a-=5120;return a==0?t:a==1?u:a==2?pa:a==4?v:a==6?x:a==5||a==28922||a==28520||a==30779||a==30782?w:qa},W=a=>{var b=M.xd;if(b){var c=b.Kc[a];typeof c=="number"&&(b.Kc[a]=c=M.getUniformLocation(b,b.td[a]+(c>0?`[${c}]`:"")));return c}T||=1282},X=[],Pb=[],Y=a=>{var b=Lb(a)+1,c=Qb(b);K(a,c,b);return c},Tb=a=>{var b=Rb();a();Sb(b)},Ub=(a,b,c,d)=>{var e={string:p=>{var r=0;p!==null&&p!==void 0&&p!==0&&(r=Y(p));return r},array:p=>{var r=
Qb(p.length);t.set(p,r);return r}};a=g["_"+a];var h=[],f=0;if(d)for(var l=0;l<d.length;l++){var n=e[c[l]];n?(f===0&&(f=Rb()),h[l]=n(d[l])):h[l]=d[l]}c=a(...h);return c=function(p){f!==0&&Sb(f);return b==="string"?p?F(p):"":b==="boolean"?!!p:p}(c)};g.requestAnimationFrame=Ma;g.pauseMainLoop=Ya;g.resumeMainLoop=function(){Pa++;var a=Ha,b=Ia,c=D;D=null;Xa(c,0,!1,Qa,!0);Oa(a,b);E()};g.preMainLoop&&Va.push(g.preMainLoop);g.postMainLoop&&Wa.push(g.postMainLoop);for(let a=0;a<32;++a)Ib.push(Array(a));
for(var Vb=new Float32Array(288),Z=0;Z<=288;++Z)X[Z]=Vb.subarray(0,Z);var Wb=new Int32Array(288);for(Z=0;Z<=288;++Z)Pb[Z]=Wb.subarray(0,Z);g.noExitRuntime&&(Ba=g.noExitRuntime);g.printErr&&(k=g.printErr);g.wasmBinary&&(m=g.wasmBinary);g.arguments&&(da=g.arguments);g.thisProgram&&(ea=g.thisProgram);if(g.preInit)for(typeof g.preInit=="function"&&(g.preInit=[g.preInit]);g.preInit.length>0;)g.preInit.shift()();g.ccall=Ub;
g.cwrap=(a,b,c,d)=>{var e=!c||c.every(h=>h==="number"||h==="boolean");return b!=="string"&&e&&!d?g["_"+a]:(...h)=>Ub(a,b,c,h,d)};
var Xb,Yb,Zb,$b,ac,bc,cc,dc,ec,fc,hc,ic,jc,kc,L,lc,Sb,Qb,Rb,oa,db,mc={gb:()=>ra(""),fb:()=>{Ba=!1;Ca=0},cb:(a,b)=>{B[a]&&(clearTimeout(B[a].id),delete B[a]);if(!b)return 0;var c=setTimeout(()=>{delete B[a];Ga(()=>lc(a,performance.now()))},b);B[a]={id:c,ae:b};return 0},Qa:()=>{Ya();D=null},ia:()=>globalThis.devicePixelRatio??1,ka:(a,b,c)=>{a=G(a);if(!a)return-4;a=bb(a);y[b>>3]=a.width;y[c>>3]=a.height;return 0},A:()=>performance.now(),Ra:()=>performance.now(),Xa:(a,b)=>{function c(d){H(a)(d,b)&&requestAnimationFrame(c)}
return requestAnimationFrame(c)},db:a=>{var b=u.length;a>>>=0;if(a>2147483648)return!1;for(var c=1;c<=4;c*=2){var d=b*(1+.2/c);d=Math.min(d,a+100663296);a:{d=(Math.min(2147483648,Math.ceil(Math.max(a,d)/65536)*65536)-oa.buffer.byteLength+65535)/65536|0;try{oa.grow(d);na();var e=1;break a}catch(h){}e=void 0}if(e)return!0}return!1},S:(a,b,c,d)=>hb(a,b,c,d,12,"blur"),ha:(a,b,c)=>{a=G(a);if(!a)return-4;a.width=b;a.height=c;return 0},T:(a,b,c,d)=>hb(a,b,c,d,13,"focus"),R:(a,b,c,d)=>{if(!I.fullscreenEnabled())return-1;
a=G(a);if(!a)return-4;ib(a,b,c,d,"webkitfullscreenchange");return ib(a,b,c,d,"fullscreenchange")},aa:(a,b,c,d)=>jb(a,b,c,d,2,"keydown"),_:(a,b,c,d)=>jb(a,b,c,d,1,"keypress"),$:(a,b,c,d)=>jb(a,b,c,d,3,"keyup"),Ya:(a,b,c)=>{a=H(a);Xa(a,b,c)},ga:(a,b,c,d)=>lb(a,b,c,d,5,"mousedown"),da:(a,b,c,d)=>lb(a,b,c,d,33,"mouseenter"),ca:(a,b,c,d)=>lb(a,b,c,d,34,"mouseleave"),ea:(a,b,c,d)=>lb(a,b,c,d,8,"mousemove"),fa:(a,b,c,d)=>lb(a,b,c,d,6,"mouseup"),V:(a,b,c,d)=>document.body?.requestPointerLock?(a=G(a))?mb(a,
b,c,d):-4:-1,U:(a,b,c,d)=>document.body?.requestPointerLock?(a=G(a))?nb(a,b,c,d):-4:-1,ja:(a,b,c,d)=>ob(a,b,c,d),W:(a,b,c,d)=>pb(a,b,c,d,25,"touchcancel"),X:(a,b,c,d)=>pb(a,b,c,d,23,"touchend"),Y:(a,b,c,d)=>pb(a,b,c,d,24,"touchmove"),Z:(a,b,c,d)=>pb(a,b,c,d,22,"touchstart"),Q:(a,b,c,d)=>{Fb(a,b,c,d,31,"webglcontextlost");return 0},P:(a,b,c,d)=>{Fb(a,b,c,d,32,"webglcontextrestored");return 0},ba:(a,b,c,d)=>(a=G(a))?typeof a.onwheel!="undefined"?Gb(a,b,c,d):-1:-4,Va:(a,b)=>{var c=b>>2;b={alpha:!!t[b+
0],depth:!!t[b+1],stencil:!!t[b+2],antialias:!!t[b+3],premultipliedAlpha:!!t[b+4],preserveDrawingBuffer:!!t[b+5],powerPreference:Hb[v[c+2]],failIfMajorPerformanceCaveat:!!t[b+12],jd:v[c+4],Rd:v[c+5],ed:t[b+24],yd:t[b+25],Ud:v[c+7],Zd:t[b+32]};a=G(a);return!a||b.yd?0:Eb(a,b)},Ua:a=>{V=yb[a];g.ctx=M=V?.ad;return!a||M?0:-5},n:a=>M.activeTexture(a),C:(a,b)=>{M.attachShader(P[a],R[b])},a:(a,b)=>{a==35051?M.cd=b:a==35052&&(M.Jc=b);M.bindBuffer(a,O[b])},w:(a,b,c)=>{M.bindBufferBase(a,b,O[c])},yb:(a,b,c,
d,e)=>{M.bindBufferRange(a,b,O[c],d,e)},h:(a,b)=>{M.bindFramebuffer(a,vb[b])},Jb:(a,b)=>{M.bindRenderbuffer(a,wb[b])},m:(a,b)=>{M.bindSampler(a,S[b])},c:(a,b)=>{M.bindTexture(a,Q[b])},O:a=>{M.bindVertexArray(xb[a])},J:(a,b,c,d)=>M.blendColor(a,b,c,d),K:(a,b)=>M.blendEquationSeparate(a,b),L:(a,b,c,d)=>M.blendFuncSeparate(a,b,c,d),ib:(a,b,c,d,e,h,f,l,n,p)=>M.blitFramebuffer(a,b,c,d,e,h,f,l,n,p),Ea:(a,b,c,d)=>{V.version>=2?c&&b?M.bufferData(a,u,d,c,b):M.bufferData(a,b,d):M.bufferData(a,c?u.subarray(c,
c+b):b,d)},D:(a,b,c,d)=>{var e=u;V.version>=2?c&&M.bufferSubData(a,b,e,d,c):M.bufferSubData(a,b,e.subarray(d,d+c))},Gb:a=>M.checkFramebufferStatus(a),Fb:(a,b,c,d)=>M.clearBufferfi(a,b,c,d),qa:(a,b,c)=>{M.clearBufferfv(a,b,x,c>>2)},Eb:(a,b,c)=>{M.clearBufferiv(a,b,v,c>>2)},o:(a,b,c,d)=>{M.colorMask(!!a,!!b,!!c,!!d)},Nb:a=>{M.compileShader(R[a])},t:(a,b,c,d,e,h,f,l,n)=>{V.version>=2?M.Jc||!l?M.compressedTexSubImage2D(a,b,c,d,e,h,f,l,n):M.compressedTexSubImage2D(a,b,c,d,e,h,f,u,n,l):M.compressedTexSubImage2D(a,
b,c,d,e,h,f,u.subarray(n,n+l))},Aa:(a,b,c,d,e,h,f,l,n,p,r)=>{M.Jc?M.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,p,r):M.compressedTexSubImage3D(a,b,c,d,e,h,f,l,n,u,r,p)},Tb:()=>{var a=Cb(P),b=M.createProgram();b.name=a;b.Nc=b.Lc=b.Mc=0;b.Zc=1;P[a]=b;return a},Qb:a=>{var b=Cb(R);R[b]=M.createShader(a);return b},G:a=>M.cullFace(a),Ha:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=O[d];e&&(M.deleteBuffer(e),e.name=0,O[d]=null,d==M.cd&&(M.cd=0),d==M.Jc&&(M.Jc=0))}},v:(a,b)=>{for(var c=0;c<a;++c){var d=
v[b+c*4>>2],e=vb[d];e&&(M.deleteFramebuffer(e),e.name=0,vb[d]=null)}},l:a=>{if(a){var b=P[a];b?(M.deleteProgram(b),b.name=0,P[a]=null):T||=1281}},E:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=wb[d];e&&(M.deleteRenderbuffer(e),e.name=0,wb[d]=null)}},F:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=S[d];e&&(M.deleteSampler(e),e.name=0,S[d]=null)}},p:a=>{if(a){var b=R[a];b?(M.deleteShader(b),R[a]=null):T||=1281}},i:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2],e=Q[d];e&&(M.deleteTexture(e),e.name=
0,Q[d]=null)}},Ga:(a,b)=>{for(var c=0;c<a;c++){var d=v[b+c*4>>2];M.deleteVertexArray(xb[d]);xb[d]=null}},y:a=>M.depthFunc(a),x:a=>{M.depthMask(!!a)},d:a=>M.disable(a),M:a=>{M.disableVertexAttribArray(a)},lb:(a,b,c)=>{M.drawArrays(a,b,c)},mb:(a,b,c,d)=>{M.drawArraysInstanced(a,b,c,d)},sa:(a,b)=>{for(var c=Ib[a],d=0;d<a;d++)c[d]=v[b+d*4>>2];M.drawBuffers(c)},nb:(a,b,c,d)=>{M.drawElements(a,b,c,d)},ob:(a,b,c,d,e)=>{M.drawElementsInstanced(a,b,c,d,e)},g:a=>M.enable(a),zb:a=>{M.enableVertexAttribArray(a)},
j:(a,b,c,d)=>{M.framebufferRenderbuffer(a,b,c,wb[d])},e:(a,b,c,d,e)=>{M.framebufferTexture2D(a,b,c,Q[d],e)},B:(a,b,c,d,e)=>{M.framebufferTextureLayer(a,b,Q[c],d,e)},H:a=>M.frontFace(a),Fa:(a,b)=>{U(a,b,"createBuffer",O)},N:(a,b)=>{U(a,b,"createFramebuffer",vb)},Kb:(a,b)=>{U(a,b,"createRenderbuffer",wb)},ya:(a,b)=>{U(a,b,"createSampler",S)},Da:(a,b)=>{U(a,b,"createTexture",Q)},Pa:(a,b)=>{U(a,b,"createVertexArray",xb)},Lb:(a,b)=>M.getAttribLocation(P[a],b?F(b):""),b:(a,b)=>Kb(a,b),Sb:(a,b,c,d)=>{a=
M.getProgramInfoLog(P[a]);a===null&&(a="(unknown error)");b=b>0&&d?K(a,d,b):0;c&&(v[c>>2]=b)},va:(a,b,c)=>{if(c)if(a>=ub)T||=1281;else if(a=P[a],b==35716)a=M.getProgramInfoLog(a),a===null&&(a="(unknown error)"),v[c>>2]=a.length+1;else if(b==35719){if(!a.Nc){var d=M.getProgramParameter(a,35718);for(b=0;b<d;++b)a.Nc=Math.max(a.Nc,M.getActiveUniform(a,b).name.length+1)}v[c>>2]=a.Nc}else if(b==35722){if(!a.Lc)for(d=M.getProgramParameter(a,35721),b=0;b<d;++b)a.Lc=Math.max(a.Lc,M.getActiveAttrib(a,b).name.length+
1);v[c>>2]=a.Lc}else if(b==35381){if(!a.Mc)for(d=M.getProgramParameter(a,35382),b=0;b<d;++b)a.Mc=Math.max(a.Mc,M.getActiveUniformBlockName(a,b).length+1);v[c>>2]=a.Mc}else v[c>>2]=M.getProgramParameter(a,b);else T||=1281},Mb:(a,b,c,d)=>{a=M.getShaderInfoLog(R[a]);a===null&&(a="(unknown error)");b=b>0&&d?K(a,d,b):0;c&&(v[c>>2]=b)},ta:(a,b,c)=>{c?b==35716?(a=M.getShaderInfoLog(R[a]),a===null&&(a="(unknown error)"),v[c>>2]=a?a.length+1:0):b==35720?(a=M.getShaderSource(R[a]),v[c>>2]=a?a.length+1:0):v[c>>
2]=M.getShaderParameter(R[a],b):T||=1281},Na:(a,b)=>{if(V.version<2)return T||=1282,0;var c=zb[a];if(c)return b<0||b>=c.length?(T||=1281,0):c[b];switch(a){case 7939:return c=Jb().map(Mb),c=zb[a]=c,b<0||b>=c.length?(T||=1281,0):c[b];default:return T||=1280,0}},ua:(a,b)=>{b=b?F(b):"";if(a=P[a]){var c=a,d=c.Kc,e=c.ud,h;if(!d){c.Kc=d={};c.td={};var f=M.getProgramParameter(c,35718);for(h=0;h<f;++h){var l=M.getActiveUniform(c,h);var n=l.name;l=l.size;var p=Nb(n);p=p>0?n.slice(0,p):n;var r=c.Zc;c.Zc+=l;
e[p]=[l,r];for(n=0;n<l;++n)d[r]=n,c.td[r++]=p}}c=a.Kc;d=0;h=b;e=Nb(b);e>0&&(d=b.slice(e+1),d=parseInt(d)>>>0,h=b.slice(0,e));if((e=a.ud[h])&&d<e[0]&&(d+=e[1],c[d]=c[d]||M.getUniformLocation(a,b)))return d}else T||=1281;return-1},hb:(a,b,c)=>{for(var d=Ib[b],e=0;e<b;e++)d[e]=v[c+e*4>>2];M.invalidateFramebuffer(a,d)},wa:a=>{a=P[a];M.linkProgram(a);a.Kc=0;a.ud={}},Oa:(a,b)=>{a==3317?Ab=b:a==3314&&(Bb=b);M.pixelStorei(a,b)},I:(a,b)=>M.polygonOffset(a,b),kb:a=>M.readBuffer(a),Ib:(a,b,c,d,e)=>M.renderbufferStorageMultisample(a,
b,c,d,e),xa:(a,b,c)=>{M.samplerParameterf(S[a],b,c)},f:(a,b,c)=>{M.samplerParameteri(S[a],b,c)},ra:(a,b,c,d)=>M.scissor(a,b,c,d),Ob:(a,b,c,d)=>{for(var e="",h=0;h<b;++h){var f=(f=w[c+h*4>>2])?F(f,d?w[d+h*4>>2]:void 0):"";e+=f}M.shaderSource(R[a],e)},La:(a,b,c)=>M.stencilFunc(a,b,c),pa:(a,b,c,d)=>M.stencilFuncSeparate(a,b,c,d),q:a=>M.stencilMask(a),Ka:(a,b,c)=>M.stencilOp(a,b,c),oa:(a,b,c,d)=>M.stencilOpSeparate(a,b,c,d),Ca:(a,b,c,d,e)=>M.texStorage2D(a,b,c,d,e),Ba:(a,b,c,d,e,h)=>M.texStorage3D(a,
b,c,d,e,h),s:(a,b,c,d,e,h,f,l,n)=>{if(V.version>=2){if(M.Jc){M.texSubImage2D(a,b,c,d,e,h,f,l,n);return}if(n){var p=Ob(l);M.texSubImage2D(a,b,c,d,e,h,f,l,p,n>>>31-Math.clz32(p.BYTES_PER_ELEMENT));return}}if(n){p=Ob(l);var r=h*(({5:3,6:4,8:2,29502:3,29504:4,26917:2,26918:2,29846:3,29847:4}[f-6402]||1)*p.BYTES_PER_ELEMENT*(Bb||e)+Ab-1&-Ab);n=p.subarray(n>>>31-Math.clz32(p.BYTES_PER_ELEMENT),n+r>>>31-Math.clz32(p.BYTES_PER_ELEMENT))}else n=null;M.texSubImage2D(a,b,c,d,e,h,f,l,n)},za:(a,b,c,d,e,h,f,l,
n,p,r)=>{if(M.Jc)M.texSubImage3D(a,b,c,d,e,h,f,l,n,p,r);else if(r){var N=Ob(p);M.texSubImage3D(a,b,c,d,e,h,f,l,n,p,N,r>>>31-Math.clz32(N.BYTES_PER_ELEMENT))}else M.texSubImage3D(a,b,c,d,e,h,f,l,n,p,null)},xb:(a,b,c)=>{if(V.version>=2)b&&M.uniform1fv(W(a),x,c>>2,b);else{if(b<=288)for(var d=X[b],e=0;e<b;++e)d[e]=x[c+4*e>>2];else d=x.subarray(c>>2,c+b*4>>2);M.uniform1fv(W(a),d)}},Rb:(a,b)=>{M.uniform1i(W(a),b)},tb:(a,b,c)=>{if(V.version>=2)b&&M.uniform1iv(W(a),v,c>>2,b);else{if(b<=288)for(var d=Pb[b],
e=0;e<b;++e)d[e]=v[c+4*e>>2];else d=v.subarray(c>>2,c+b*4>>2);M.uniform1iv(W(a),d)}},wb:(a,b,c)=>{if(V.version>=2)b&&M.uniform2fv(W(a),x,c>>2,b*2);else{if(b<=144){b*=2;for(var d=X[b],e=0;e<b;e+=2)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2]}else d=x.subarray(c>>2,c+b*8>>2);M.uniform2fv(W(a),d)}},sb:(a,b,c)=>{if(V.version>=2)b&&M.uniform2iv(W(a),v,c>>2,b*2);else{if(b<=144){b*=2;for(var d=Pb[b],e=0;e<b;e+=2)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2]}else d=v.subarray(c>>2,c+b*8>>2);M.uniform2iv(W(a),d)}},vb:(a,
b,c)=>{if(V.version>=2)b&&M.uniform3fv(W(a),x,c>>2,b*3);else{if(b<=96){b*=3;for(var d=X[b],e=0;e<b;e+=3)d[e]=x[c+4*e>>2],d[e+1]=x[c+(4*e+4)>>2],d[e+2]=x[c+(4*e+8)>>2]}else d=x.subarray(c>>2,c+b*12>>2);M.uniform3fv(W(a),d)}},rb:(a,b,c)=>{if(V.version>=2)b&&M.uniform3iv(W(a),v,c>>2,b*3);else{if(b<=96){b*=3;for(var d=Pb[b],e=0;e<b;e+=3)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2]}else d=v.subarray(c>>2,c+b*12>>2);M.uniform3iv(W(a),d)}},ub:(a,b,c)=>{if(V.version>=2)b&&M.uniform4fv(W(a),
x,c>>2,b*4);else{if(b<=72){var d=X[4*b],e=x;c>>=2;b*=4;for(var h=0;h<b;h+=4){var f=c+h;d[h]=e[f];d[h+1]=e[f+1];d[h+2]=e[f+2];d[h+3]=e[f+3]}}else d=x.subarray(c>>2,c+b*16>>2);M.uniform4fv(W(a),d)}},qb:(a,b,c)=>{if(V.version>=2)b&&M.uniform4iv(W(a),v,c>>2,b*4);else{if(b<=72){b*=4;for(var d=Pb[b],e=0;e<b;e+=4)d[e]=v[c+4*e>>2],d[e+1]=v[c+(4*e+4)>>2],d[e+2]=v[c+(4*e+8)>>2],d[e+3]=v[c+(4*e+12)>>2]}else d=v.subarray(c>>2,c+b*16>>2);M.uniform4iv(W(a),d)}},pb:(a,b,c,d)=>{if(V.version>=2)b&&M.uniformMatrix4fv(W(a),
!!c,x,d>>2,b*16);else{if(b<=18){var e=X[16*b],h=x;d>>=2;b*=16;for(var f=0;f<b;f+=16){var l=d+f;e[f]=h[l];e[f+1]=h[l+1];e[f+2]=h[l+2];e[f+3]=h[l+3];e[f+4]=h[l+4];e[f+5]=h[l+5];e[f+6]=h[l+6];e[f+7]=h[l+7];e[f+8]=h[l+8];e[f+9]=h[l+9];e[f+10]=h[l+10];e[f+11]=h[l+11];e[f+12]=h[l+12];e[f+13]=h[l+13];e[f+14]=h[l+14];e[f+15]=h[l+15]}}else e=x.subarray(d>>2,d+b*64>>2);M.uniformMatrix4fv(W(a),!!c,e)}},k:a=>{a=P[a];M.useProgram(a);M.xd=a},Ab:(a,b)=>{M.vertexAttribDivisor(a,b)},Bb:(a,b,c,d,e)=>{M.vertexAttribIPointer(a,
b,c,d,e)},Cb:(a,b,c,d,e,h)=>{M.vertexAttribPointer(a,b,c,!!d,e,h)},r:(a,b,c,d)=>M.viewport(a,b,c,d),eb:Ea,Wb:function(){g.md=a=>{Yb()!=0&&(a.preventDefault(),a.returnValue=" ")};window.addEventListener("beforeunload",g.md)},_a:function(){g.sd=a=>{var b=a.clipboardData.getData("text");Tb(()=>{var c=Y(b);Xb(c)})};window.addEventListener("paste",g.sd)},Ta:function(){g.$d=[];g.nd=b=>{b.stopPropagation();b.preventDefault()};g.od=b=>{b.stopPropagation();b.preventDefault()};g.pd=b=>{b.stopPropagation();
b.preventDefault()};g.qd=b=>{b.stopPropagation();b.preventDefault();var c=b.dataTransfer.files;g.rd=c;Zb(c.length);for(let e=0;e<c.length;e++)Tb(()=>{var h=Y(c[e].name);$b(e,h)});var d=0;b.shiftKey&&(d|=1);b.ctrlKey&&(d|=2);b.altKey&&(d|=4);b.metaKey&&(d|=8);ac(b.clientX,b.clientY,d)};var a=g.Gc;a.addEventListener("dragenter",g.nd,!1);a.addEventListener("dragleave",g.od,!1);a.addEventListener("dragover",g.pd,!1);a.addEventListener("drop",g.qd,!1)},Hb:function(){var a=document.getElementById("sokol-app-favicon");
a&&document.head.removeChild(a)},Pb:function(a){g.Pc&&(URL.revokeObjectURL(g.Pc[a].Ed),g.Pc[a]=null)},Sa:function(a){var b=g.rd;return a<0||a>=b.length?0:b[a].size},Ma:function(a,b,c,d,e){var h=new FileReader;h.onload=f=>{f=f.target.result;f.byteLength>d?bc(a,0,1,b,0,c,d,e):(u.set(new Uint8Array(f),c),bc(a,1,0,b,f.byteLength,c,d,e))};h.onerror=()=>{bc(a,0,2,b,0,c,d,e)};h.readAsArrayBuffer(g.rd[a])},Ia:function(a,b){b!==0&&(document.title=b?F(b):"");a=a?F(a):"";g.canvas!==void 0&&(typeof g.canvas===
"object"?ab[a]=g.canvas:console.warn("sokol_app.h: Module['canvas'] is set but is not an object"));g.Gc=G(a);g.Gc||console.warn("sokol_app.h: can't find html5_canvas_selector ",a);g.Gc.requestPointerLock||console.warn("sokol_app.h: target doesn't support requestPointerLock: ",a)},Vb:function(){window.removeEventListener("beforeunload",g.md)},Wa:function(){window.removeEventListener("paste",g.sd)},Ja:function(){var a=g.Gc;a.removeEventListener("dragenter",g.nd);a.removeEventListener("dragleave",g.od);
a.removeEventListener("dragover",g.pd);a.removeEventListener("drop",g.qd)},u:function(){g.Gc&&g.Gc.requestPointerLock&&g.Gc.requestPointerLock()},Ub:function(a,b,c){if(g.Gc){if(b===0)a="none";else if(c!=0)a=g.Pc[a].Gd;else switch(a){case 0:a="auto";break;case 1:a="default";break;case 2:a="text";break;case 3:a="crosshair";break;case 4:a="pointer";break;case 5:a="ew-resize";break;case 6:a="ns-resize";break;case 7:a="nwse-resize";break;case 8:a="nesw-resize";break;case 9:a="all-scroll";break;case 10:a=
"not-allowed";break;default:a="auto"}g.Gc.style.cursor=a}},Db:function(a,b,c){var d=document.createElement("canvas");d.width=a;d.height=b;var e=d.getContext("2d"),h=e.createImageData(a,b);h.data.set(u.subarray(c,c+a*b*4));e.putImageData(h,0,0);a=document.createElement("link");a.id="sokol-app-favicon";a.rel="shortcut icon";a.href=d.toDataURL();document.head.appendChild(a)},Za:function(){var a=(new URLSearchParams(window.location.search)).entries();for(let b=a.next();!b.done;b=a.next()){let c=b.value[0],
d=b.value[1];Tb(()=>{var e=Y(c),h=Y(d);ec(e,h)})}},ab:function(){return g.Hc?g.Hc.bufferSize:0},jb:function(a,b,c){g.yc=null;g.Hc=null;typeof AudioContext!=="undefined"?g.yc=new AudioContext({sampleRate:a,latencyHint:"interactive"}):(g.yc=null,console.log("sokol_audio.h: no WebAudio support"));if(g.yc){console.log("sokol_audio.h: sample rate ",g.yc.sampleRate);g.Hc=g.yc.createScriptProcessor(c,0,b);g.Hc.onaudioprocess=e=>{var h=e.outputBuffer.length,f=dc(h);if(f){let l=e.outputBuffer.numberOfChannels;
for(let n=0;n<l;n++){let p=e.outputBuffer.getChannelData(n);for(let r=0;r<h;r++)p[r]=x[(f>>2)+(l*r+n)]}}};g.Hc.connect(g.yc.destination);let d=()=>{if(g.yc){let e=g.yc.state;e!=="suspended"&&e!=="interrupted"||g.yc.resume().catch(()=>{console.warn("sokol_audio.h: webaudio resume failed")})}};g.yc.onstatechange=d;document.addEventListener("visibilitychange",()=>{document.visibilityState==="visible"&&d()});document.addEventListener("click",d,{once:!0});document.addEventListener("touchend",d,{once:!0});
document.addEventListener("keydown",d,{once:!0});return 1}return 0},bb:function(){return g.yc?g.yc.sampleRate:0},na:function(){var a=g.yc;a!==null&&(g.Hc&&g.Hc.disconnect(),a.close(),g.yc=null,g.Hc=null)},$a:function(){if(g.yc){let a=g.yc.state;return a==="suspended"||a==="interrupted"?1:0}return 0},z:function(a,b,c,d,e,h){var f=b?F(b):"";b=new Headers;d>0&&b.append("Range",`bytes=${c}-${c+d-1}`);fetch(f,{method:"GET",headers:b}).then(l=>{l.ok?l.arrayBuffer().then(n=>{n=new Uint8Array(n);n.length<=
h?(u.set(n,e),hc(a,d,n.length)):jc(a)}).catch(n=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,n);kc(a)}):ic(a,l.status)}).catch(l=>{console.error(`sokol_fetch.h: GET ${f} failed with: `,l);kc(a)})},ma:function(a,b){var c=b?F(b):"";fetch(c,{method:"HEAD"}).then(d=>{d.ok?(d=d.headers.get("Content-Length"),d===null?(console.warn(`sokol_fetch.h: HEAD ${c} response has no Content-Length`),kc(a)):fc(a,Number(d))):ic(a,d.status)}).catch(d=>{console.error(`sokol_fetch.h: HEAD ${c} failed with: `,
d);kc(a)})},la:function(a,b){b=b?F(b):"";switch(a){case 0:console.error(b);break;case 1:console.error(b);break;case 2:console.warn(b);break;default:console.info(b)}}};function nc(a=[]){var b=cc;a.unshift(ea);var c=a.length,d=Qb((c+1)*4),e=d,h;for(h of a)w[e>>2]=Y(h),e+=4;w[e>>2]=0;try{var f=b(c,d);ma=f;Ea(f)}catch(l){Da(l)}}
function oc(a=da){function b(){g.calledRun=!0;if(!q){pc.Yb();g.onRuntimeInitialized?.();g.noInitialRun||nc(a);if(g.postRun)for(typeof g.postRun=="function"&&(g.postRun=[g.postRun]);g.postRun.length;){var c=g.postRun.shift();ya.push(c)}xa(ya)}}if(z>0)A=oc;else{if(g.preRun)for(typeof g.preRun=="function"&&(g.preRun=[g.preRun]);g.preRun.length;)Aa();xa(za);z>0?A=oc:g.setStatus?(g.setStatus("Running..."),setTimeout(()=>{setTimeout(()=>g.setStatus(""),1);b()},1)):b()}}var pc;
(async function(){function a(c){c=pc=c.exports;g._gx_state_size=c.Zb;g._gx_state_ptr=c._b;g._gx_state_save=c.$b;g._gx_state_load=c.ac;Xb=g.__sapp_emsc_onpaste=c.bc;Yb=g.__sapp_html5_get_ask_leave_site=c.cc;Zb=g.__sapp_emsc_begin_drop=c.dc;$b=g.__sapp_emsc_drop=c.ec;ac=g.__sapp_emsc_end_drop=c.fc;bc=g.__sapp_emsc_invoke_fetch_cb=c.gc;g.__sapp_emsc_set_fullscreen_flag=c.hc;cc=g._main=c.ic;dc=g.__saudio_emsc_pull=c.jc;ec=g.__sargs_add_kvp=c.kc;fc=g.__sfetch_emsc_head_response=c.lc;hc=g.__sfetch_emsc_get_response=
c.mc;ic=g.__sfetch_emsc_failed_http_status=c.nc;jc=g.__sfetch_emsc_failed_buffer_too_small=c.oc;kc=g.__sfetch_emsc_failed_other=c.pc;L=c.qc;g._fs_emsc_alloc=c.rc;g._fs_emsc_load_snapshot_callback=c.sc;lc=c.tc;Sb=c.vc;Qb=c.wc;Rb=c.xc;oa=c.Xb;db=c.uc;na();z--;g.monitorRunDependencies?.(z);z==0&&A&&(c=A,A=null,c());return pc}z++;g.monitorRunDependencies?.(z);var b={a:mc};if(g.instantiateWasm)return new Promise(c=>{g.instantiateWasm(b,(d,e)=>{c(a(d,e))})});sa??=g.locateFile?g.locateFile("cpc.wasm",ia):
ia+"cpc.wasm";return function(c){return a(c.instance)}(await va(b))})();oc();
